apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGODB_URI: "mongodb://momo:momo$99@mongodb:27017/mp3s?authSource=admin" #nodeip:nodeport
